### ISSUE TITLE
A way to tell if it's a new install or upgrade?

### ISSUE THREAD

**Issue by jfsso** [KeithYokoma/Fit#2]
There's a logic I want to execute only for upgrades of my app, not new installs. Is there a way to tell/annotate a method to only be executed for upgrades?

**Comment by KeithYokoma** [comment]
Fit does not have any way to do that on the current version. We should consider adding new annotation.

**Comment by KeithYokoma** [comment]
@jfsso It's coming on the next release!

**Comment by KeithYokoma** [comment]
Released!
